services:
  captcha-service:
    container_name: captcha-app
    build: . 
    depends_on:
      - db
    ports:
     - "3000:3000"
    environment:
        - NODE_ENV=development
        - PORT=3000
        - DB_HOST=db
        - DB_PORT=5432
        - DB_USER=postgres
        - DB_PASSWORD=postgres
        - DB_NAME=captcha_db
    restart: always

  db: 
    image: postgres:latest  
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: captcha_db 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 

volumes:
  postgres_data: